baseURL = "/"
languageCode = "en-us"
title = "COVID Response Team - Richmond, Virginia"
themesDir = "themes"
theme = "hugo-serif-theme"
publishDir = "docs"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/covidlogos.svg"
    alt = "COVID Response Team"

  [params.homepage_meta_tags]
    meta_description = "Richmond, Virginia based COVID-19 & Virus Disinfection Services"
    meta_og_title = "COVID-19 & Virus Disinfection"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = "COVID Response Team is a viral disinfection business."
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
